import type { NbaNewsSource } from "./types";

export const NBA_LEAGUE_SOURCES = [
  {
    displayName: "NBA",
    platform: "x",
    sourceType: "official_league",
    tier: "T0",
    trustScore: 95,
    handle: "NBA",
    sourceUrl: "https://x.com/NBA",
    teamCode: null,
    primaryTopics: ["league", "game"],
    usagePolicy: "official_confirmation",
    isActive: true,
    isPublishEligible: true,
    verifyStatus: "needs_manual_check",
    verifiedAt: null,
    notes: "League official account for schedules, awards, and major announcements.",
  },
  {
    displayName: "NBA Communications",
    platform: "x",
    sourceType: "official_league",
    tier: "T0",
    trustScore: 98,
    handle: "NBAPR",
    sourceUrl: "https://x.com/NBAPR",
    teamCode: null,
    primaryTopics: ["league", "discipline"],
    usagePolicy: "official_confirmation",
    isActive: true,
    isPublishEligible: true,
    verifyStatus: "needs_manual_check",
    verifiedAt: null,
    notes: "Primary official source for league communications, awards, discipline, and rule notices.",
  },
  {
    displayName: "NBA Official",
    platform: "x",
    sourceType: "official_league",
    tier: "T0",
    trustScore: 92,
    handle: "NBAOfficial",
    sourceUrl: "https://x.com/NBAOfficial",
    teamCode: null,
    primaryTopics: ["league", "discipline"],
    usagePolicy: "official_confirmation",
    isActive: true,
    isPublishEligible: true,
    verifyStatus: "needs_manual_check",
    verifiedAt: null,
    notes: "Support source for officiating and rules context.",
  },
] satisfies readonly NbaNewsSource[];

export const NBA_INSIDER_SOURCES = [
  {
    displayName: "Shams Charania",
    platform: "x",
    sourceType: "tier_1_insider",
    tier: "T1",
    trustScore: 90,
    handle: "ShamsCharania",
    sourceUrl: "https://x.com/ShamsCharania",
    teamCode: null,
    primaryTopics: ["trade", "signing", "injury", "league", "free_agency"],
    usagePolicy: "single_source_draft_admin_approval",
    isActive: true,
    isPublishEligible: true,
    verifyStatus: "needs_manual_check",
    verifiedAt: null,
    notes: "Single-source reports require attribution in headline or lead.",
  },
  {
    displayName: "Marc Stein",
    platform: "x",
    sourceType: "tier_1_insider",
    tier: "T1",
    trustScore: 88,
    handle: "TheSteinLine",
    sourceUrl: "https://x.com/TheSteinLine",
    teamCode: null,
    primaryTopics: ["trade", "signing", "league", "free_agency"],
    usagePolicy: "single_source_draft_admin_approval",
    isActive: true,
    isPublishEligible: true,
    verifyStatus: "needs_manual_check",
    verifiedAt: null,
    notes: "Strong source for free agency, trade market, and league context.",
  },
  {
    displayName: "Brian Windhorst",
    platform: "x",
    sourceType: "tier_2_insider",
    tier: "T2",
    trustScore: 78,
    handle: "WindhorstESPN",
    sourceUrl: "https://x.com/WindhorstESPN",
    teamCode: null,
    primaryTopics: ["league", "analysis", "trade"],
    usagePolicy: "cross_check_required",
    isActive: true,
    isPublishEligible: true,
    verifyStatus: "needs_manual_check",
    verifiedAt: null,
    notes: "Use mostly for league context and corroboration.",
  },
  {
    displayName: "Tim Bontemps",
    platform: "x",
    sourceType: "tier_2_insider",
    tier: "T2",
    trustScore: 76,
    handle: "TimBontemps",
    sourceUrl: "https://x.com/TimBontemps",
    teamCode: null,
    primaryTopics: ["league", "analysis", "game"],
    usagePolicy: "cross_check_required",
    isActive: true,
    isPublishEligible: true,
    verifyStatus: "needs_manual_check",
    verifiedAt: null,
    notes: "ESPN reporting and analysis source; confirm current role before production seed.",
  },
  {
    displayName: "Chris Haynes",
    platform: "x",
    sourceType: "tier_2_insider",
    tier: "T2",
    trustScore: 77,
    handle: "ChrisBHaynes",
    sourceUrl: "https://x.com/ChrisBHaynes",
    teamCode: null,
    primaryTopics: ["trade", "signing", "quote", "free_agency"],
    usagePolicy: "single_source_draft_admin_approval",
    isActive: true,
    isPublishEligible: true,
    verifyStatus: "needs_manual_check",
    verifiedAt: null,
    notes: "Player-side reporting source. Keep single reports as reported_single until corroborated.",
  },
  {
    displayName: "Jake Fischer",
    platform: "x",
    sourceType: "tier_2_insider",
    tier: "T2",
    trustScore: 74,
    handle: "JakeLFischer",
    sourceUrl: "https://x.com/JakeLFischer",
    teamCode: null,
    primaryTopics: ["trade", "signing", "league", "free_agency"],
    usagePolicy: "cross_check_required",
    isActive: true,
    isPublishEligible: true,
    verifyStatus: "needs_manual_check",
    verifiedAt: null,
    notes: "Treat market notes as developing unless corroborated.",
  },
  {
    displayName: "Adrian Wojnarowski",
    platform: "x",
    sourceType: "legacy",
    tier: "legacy",
    trustScore: 0,
    handle: "wojespn",
    sourceUrl: "https://x.com/wojespn",
    teamCode: null,
    primaryTopics: ["league"],
    usagePolicy: "inactive_reference_only",
    isActive: false,
    isPublishEligible: false,
    verifyStatus: "stale",
    verifiedAt: null,
    notes: "Legacy reference only after 2024 retirement from NBA news breaking.",
  },
] satisfies readonly NbaNewsSource[];

export const NBA_ANALYST_SOURCES = [
  {
    displayName: "Zach Lowe",
    platform: "x",
    sourceType: "analyst",
    tier: "T4",
    trustScore: 62,
    handle: "ZachLowe_NBA",
    sourceUrl: "https://x.com/ZachLowe_NBA",
    teamCode: null,
    primaryTopics: ["analysis", "trade", "league"],
    usagePolicy: "background_context_only",
    isActive: true,
    isPublishEligible: true,
    verifyStatus: "needs_manual_check",
    verifiedAt: null,
    notes: "Use for analysis and background, not as a primary breaking source.",
  },
  {
    displayName: "Kevin O'Connor",
    platform: "x",
    sourceType: "analyst",
    tier: "T4",
    trustScore: 60,
    handle: "KevinOConnorNBA",
    sourceUrl: "https://x.com/KevinOConnorNBA",
    teamCode: null,
    primaryTopics: ["analysis", "draft", "trade"],
    usagePolicy: "background_context_only",
    isActive: true,
    isPublishEligible: true,
    verifyStatus: "needs_manual_check",
    verifiedAt: null,
    notes: "Confirm current affiliation and handle before production use.",
  },
  {
    displayName: "Bobby Marks",
    platform: "x",
    sourceType: "analyst",
    tier: "T4",
    trustScore: 64,
    handle: "BobbyMarks42",
    sourceUrl: "https://x.com/BobbyMarks42",
    teamCode: null,
    primaryTopics: ["salary_cap", "signing", "trade"],
    usagePolicy: "background_context_only",
    isActive: true,
    isPublishEligible: true,
    verifyStatus: "needs_manual_check",
    verifiedAt: null,
    notes: "Useful for salary cap and contract structure context.",
  },
  {
    displayName: "John Hollinger",
    platform: "x",
    sourceType: "analyst",
    tier: "T4",
    trustScore: 62,
    handle: "johnhollinger",
    sourceUrl: "https://x.com/johnhollinger",
    teamCode: null,
    primaryTopics: ["analysis", "trade", "league"],
    usagePolicy: "background_context_only",
    isActive: true,
    isPublishEligible: true,
    verifyStatus: "needs_manual_check",
    verifiedAt: null,
    notes: "Do not reuse paywalled article text; link and summarize independently.",
  },
] satisfies readonly NbaNewsSource[];

export const NBA_TEAM_BEAT_SOURCES = [
  ["NYK", "Ian Begley", "IanBegley", 70],
  ["NYK", "Steve Popper", "StevePopper", 66],
  ["BOS", "Jay King", "ByJayKing", 68],
  ["OKC", "Brandon Rahbar", "BrandonRahbar", 66],
  ["LAL", "Dave McMenamin", "mcten", 70],
  ["LAL", "Jovan Buha", "jovanbuha", 66],
  ["GSW", "Anthony Slater", "anthonyVslater", 68],
  ["GSW", "Marcus Thompson", "ThompsonScribe", 66],
  ["DAL", "Tim MacMahon", "espn_macmahon", 68],
  ["MIA", "Ira Winderman", "IraHeatBeat", 66],
  ["MIL", "Eric Nehm", "eric_nehm", 66],
  ["PHX", "Gerald Bourguet", "GeraldBourguet", 62],
  ["LAC", "Law Murray", "LawMurrayTheNU", 62],
  ["PHI", "Kyle Neubeck", "KyleNeubeck", 64],
].map(([teamCode, displayName, handle, trustScore]) => ({
  displayName: displayName as string,
  platform: "x",
  sourceType: "team_beat",
  tier: "T3",
  trustScore: trustScore as number,
  handle: handle as string,
  sourceUrl: `https://x.com/${handle as string}`,
  teamCode: teamCode as string,
  primaryTopics: ["trade", "signing", "injury", "quote", "game"],
  usagePolicy: "cross_check_required",
  isActive: true,
  isPublishEligible: true,
  verifyStatus: "needs_manual_check",
  verifiedAt: null,
  notes: "Team beat source for team-specific context and corroboration.",
})) satisfies readonly NbaNewsSource[];

export const NBA_OFFICIAL_TEAM_SOURCES = [
  ["ATL", "Atlanta Hawks", "ATLHawks"],
  ["BOS", "Boston Celtics", "celtics"],
  ["BKN", "Brooklyn Nets", "BrooklynNets"],
  ["CHA", "Charlotte Hornets", "hornets"],
  ["CHI", "Chicago Bulls", "chicagobulls"],
  ["CLE", "Cleveland Cavaliers", "cavs"],
  ["DAL", "Dallas Mavericks", "dallasmavs"],
  ["DEN", "Denver Nuggets", "nuggets"],
  ["DET", "Detroit Pistons", "DetroitPistons"],
  ["GSW", "Golden State Warriors", "warriors"],
  ["HOU", "Houston Rockets", "HoustonRockets"],
  ["IND", "Indiana Pacers", "Pacers"],
  ["LAC", "LA Clippers", "LAClippers"],
  ["LAL", "Los Angeles Lakers", "Lakers"],
  ["MEM", "Memphis Grizzlies", "memgrizz"],
  ["MIA", "Miami Heat", "MiamiHEAT"],
  ["MIL", "Milwaukee Bucks", "Bucks"],
  ["MIN", "Minnesota Timberwolves", "Timberwolves"],
  ["NOP", "New Orleans Pelicans", "PelicansNBA"],
  ["NYK", "New York Knicks", "nyknicks"],
  ["OKC", "Oklahoma City Thunder", "okcthunder"],
  ["ORL", "Orlando Magic", "OrlandoMagic"],
  ["PHI", "Philadelphia 76ers", "sixers"],
  ["PHX", "Phoenix Suns", "Suns"],
  ["POR", "Portland Trail Blazers", "trailblazers"],
  ["SAC", "Sacramento Kings", "SacramentoKings"],
  ["SAS", "San Antonio Spurs", "spurs"],
  ["TOR", "Toronto Raptors", "Raptors"],
  ["UTA", "Utah Jazz", "utahjazz"],
  ["WAS", "Washington Wizards", "WashWizards"],
].map(([teamCode, displayName, handle]) => ({
  displayName: displayName as string,
  platform: "x",
  sourceType: "official_team",
  tier: "T0",
  trustScore: 95,
  handle: handle as string,
  sourceUrl: `https://x.com/${handle as string}`,
  teamCode: teamCode as string,
  primaryTopics: ["league", "game", "injury", "signing"],
  usagePolicy: "official_confirmation",
  isActive: true,
  isPublishEligible: true,
  verifyStatus: "needs_manual_check",
  verifiedAt: null,
  notes: "Official team account. Use to promote matching events to official status.",
})) satisfies readonly NbaNewsSource[];

export const NBA_MEDIA_SOURCES = [
  {
    displayName: "ESPN NBA",
    platform: "x",
    sourceType: "media_account",
    tier: "T3",
    trustScore: 72,
    handle: "ESPNNBA",
    sourceUrl: "https://x.com/ESPNNBA",
    teamCode: null,
    primaryTopics: ["league", "game", "analysis"],
    usagePolicy: "cross_check_required",
    isActive: true,
    isPublishEligible: true,
    verifyStatus: "needs_manual_check",
    verifiedAt: null,
    notes: "Media account for article links and ESPN corroboration.",
  },
  {
    displayName: "AP Sports",
    platform: "x",
    sourceType: "media_account",
    tier: "T3",
    trustScore: 76,
    handle: "AP_Sports",
    sourceUrl: "https://x.com/AP_Sports",
    teamCode: null,
    primaryTopics: ["league", "game", "discipline"],
    usagePolicy: "cross_check_required",
    isActive: true,
    isPublishEligible: true,
    verifyStatus: "needs_manual_check",
    verifiedAt: null,
    notes: "Use as a conservative wire-style corroboration source.",
  },
  {
    displayName: "The Athletic NBA",
    platform: "web",
    sourceType: "media_account",
    tier: "T3",
    trustScore: 72,
    handle: null,
    sourceUrl: "https://www.nytimes.com/athletic/nba/",
    teamCode: null,
    primaryTopics: ["analysis", "trade", "league"],
    usagePolicy: "cross_check_required",
    isActive: true,
    isPublishEligible: true,
    verifyStatus: "needs_manual_check",
    verifiedAt: null,
    notes: "Do not reuse paywalled text; link and independently summarize.",
  },
] satisfies readonly NbaNewsSource[];

export const NBA_RUMOR_WATCH_SOURCES = [
  {
    displayName: "HoopsHype",
    platform: "web",
    sourceType: "rumor_watch",
    tier: "T5",
    trustScore: 35,
    handle: null,
    sourceUrl: "https://hoopshype.com/",
    teamCode: null,
    primaryTopics: ["trade", "signing", "free_agency"],
    usagePolicy: "queue_only_no_publish",
    isActive: true,
    isPublishEligible: false,
    verifyStatus: "needs_manual_check",
    verifiedAt: null,
    notes: "Rumor aggregation only. Confirm original source before any draft.",
  },
  {
    displayName: "RealGM Wiretap",
    platform: "web",
    sourceType: "rumor_watch",
    tier: "T5",
    trustScore: 40,
    handle: null,
    sourceUrl: "https://basketball.realgm.com/wiretap",
    teamCode: null,
    primaryTopics: ["trade", "signing", "league"],
    usagePolicy: "queue_only_no_publish",
    isActive: true,
    isPublishEligible: false,
    verifyStatus: "needs_manual_check",
    verifiedAt: null,
    notes: "Aggregation only. Use for event detection, not article evidence.",
  },
] satisfies readonly NbaNewsSource[];

export const NBA_NEWS_SOURCE_REGISTRY = [
  ...NBA_LEAGUE_SOURCES,
  ...NBA_INSIDER_SOURCES,
  ...NBA_ANALYST_SOURCES,
  ...NBA_TEAM_BEAT_SOURCES,
  ...NBA_OFFICIAL_TEAM_SOURCES,
  ...NBA_MEDIA_SOURCES,
  ...NBA_RUMOR_WATCH_SOURCES,
] satisfies readonly NbaNewsSource[];

export const NBA_NEWS_SOURCE_BY_HANDLE = new Map(
  NBA_NEWS_SOURCE_REGISTRY.filter((source) => source.handle).map((source) => [
    source.handle!.toLowerCase(),
    source,
  ]),
);

export const NBA_NEWS_PUBLISH_ELIGIBLE_SOURCES =
  NBA_NEWS_SOURCE_REGISTRY.filter((source) => source.isPublishEligible);
