/* global React */
// ============================================================
// MyBDR — Extra page data (Games, Organizations, Help, Pricing)
// ============================================================

// ========== GAMES (픽업 · 게스트 모집) ==========
const GAMES = [
  {
    id: 'g1',
    kind: 'pickup',        // pickup | guest | scrimmage
    title: '목요일 저녁 하남미사 픽업 · 6:4',
    court: '미사강변체육관',
    area: '하남시',
    date: '2026.04.25 (목)',
    time: '20:30 – 22:30',
    level: '중급+',
    fee: '₩5,000',
    spots: 10,
    applied: 7,
    host: 'block',
    status: 'open',
    tags: ['실내', '정기', '매주'],
  },
  {
    id: 'g2',
    kind: 'guest',
    title: '[SWEEP] 성동구민체육관 게스트 3명 모집',
    court: '성동구민체육관',
    area: '성동구',
    date: '2026.04.27 (일)',
    time: '13:00 – 15:00',
    level: '상급',
    fee: '₩8,000',
    spots: 3,
    applied: 2,
    host: 'SWEEP',
    status: 'open',
    tags: ['5v5', '스크림', '상급'],
  },
  {
    id: 'g3',
    kind: 'pickup',
    title: '의정부 회룡역 토요일 낮 픽업',
    court: '회룡역사거리 농구장',
    area: '의정부시',
    date: '2026.04.26 (토)',
    time: '12:00 – 15:00',
    level: '초-중급',
    fee: '무료',
    spots: 12,
    applied: 4,
    host: 'rdm_captain',
    status: 'open',
    tags: ['실외', '무료', '초보환영'],
  },
  {
    id: 'g4',
    kind: 'guest',
    title: '화요일 저녁 테크노마트 게스트 2명',
    court: '강변테크노마트 스카이코트',
    area: '광진구',
    date: '2026.04.29 (화)',
    time: '19:30 – 21:30',
    level: '중급',
    fee: '₩6,000',
    spots: 2,
    applied: 1,
    host: 'kings_cap',
    status: 'open',
    tags: ['실내', '5v5'],
  },
  {
    id: 'g5',
    kind: 'scrimmage',
    title: '3POINT vs 몽키즈 스크림 — 옵저버 오픈',
    court: '장충체육관',
    area: '중구',
    date: '2026.04.28 (월)',
    time: '20:00 – 22:00',
    level: '상급',
    fee: '관람 무료',
    spots: 20,
    applied: 12,
    host: '3POINT',
    status: 'open',
    tags: ['스크림', '관전'],
  },
  {
    id: 'g6',
    kind: 'pickup',
    title: '[마감임박] 반포 주말 오전 3x3',
    court: '반포종합사회복지관',
    area: '서초구',
    date: '2026.04.26 (토)',
    time: '09:00 – 11:30',
    level: '중-상급',
    fee: '₩7,000',
    spots: 6,
    applied: 5,
    host: 'pivot_mia',
    status: 'closing',
    tags: ['3v3', '마감임박'],
  },
  {
    id: 'g7',
    kind: 'pickup',
    title: '수원 청소년문화센터 새벽 농구',
    court: '수원청소년문화센터',
    area: '수원시',
    date: '2026.04.28 (월)',
    time: '06:00 – 07:30',
    level: '전연령',
    fee: '₩4,000',
    spots: 14,
    applied: 3,
    host: 'sunrise',
    status: 'open',
    tags: ['새벽', '강좌', '초보'],
  },
  {
    id: 'g8',
    kind: 'guest',
    title: 'IRON WOLVES 주말 연습경기 게스트',
    court: '용산국민체육센터',
    area: '용산구',
    date: '2026.05.03 (토)',
    time: '14:00 – 17:00',
    level: '중급+',
    fee: '₩10,000',
    spots: 4,
    applied: 0,
    host: 'IRON',
    status: 'open',
    tags: ['5v5', '연습'],
  },
];

// ========== ORGANIZATIONS (단체) ==========
const ORGS = [
  { id: 'o1', name: '서울바스켓', tag: 'SEOUL', area: '서울', teams: 12, members: 184, color: '#0F5FCC', logo: null, kind: '리그', desc: '서울 전역 12팀이 참여하는 주간 리그. 월·수·금 경기.' },
  { id: 'o2', name: '주말농구협회', tag: 'WKND', area: '수도권', teams: 28, members: 412, color: '#E31B23', logo: null, kind: '협회', desc: '주말 전용 아마추어 농구 연합. 월 1회 토너먼트.' },
  { id: 'o3', name: 'BLOCK', tag: 'BLK', area: '하남·강동·송파', teams: 4, members: 62, color: '#10B981', logo: null, kind: '동호회', desc: '동부 수도권 기반 정기 픽업 커뮤니티.' },
  { id: 'o4', name: 'SWEEP', tag: 'SWP', area: '성동·광진', teams: 3, members: 38, color: '#F59E0B', logo: null, kind: '동호회', desc: '성수·건대 중심 실내 스크림 소모임.' },
  { id: 'o5', name: '새벽의 민족', tag: 'DAWN', area: '전국', teams: 9, members: 120, color: '#8B5CF6', logo: null, kind: '동호회', desc: '평일 새벽 6시 픽업. 직장인 중심.' },
  { id: 'o6', name: '경기북부 농구연맹', tag: 'GBFL', area: '경기북부', teams: 16, members: 240, color: '#0EA5E9', logo: null, kind: '리그', desc: '의정부·남양주·고양 등 북부 지역 리그.' },
];

// ========== HELP / GLOSSARY ==========
const GLOSSARY = [
  { term: '픽업 (Pick-up)', desc: '사전 팀 구성 없이 현장에서 인원을 모아 즉석으로 진행하는 경기.' },
  { term: '게스트 (Guest)', desc: '기존 팀에 일회성으로 합류하는 외부 선수. 팀원 공백을 메우기 위함.' },
  { term: '스크림 (Scrimmage)', desc: '팀 간 합의된 비공식 연습경기. 기록은 개인 기록에만 반영.' },
  { term: '픽앤롤 (Pick & Roll)', desc: '스크리너가 스크린 후 골대 방향으로 돌아 공을 받는 공격 전술.' },
  { term: '풀코트 (Full-court)', desc: '농구장 전체를 사용하는 5v5 경기. 국내 아마추어 표준.' },
  { term: '하프코트 (Half-court)', desc: '골대 한 쪽만 사용. 3v3·픽업의 기본 형식.' },
  { term: 'OPEN', desc: '레벨 제한 없는 대회. 모든 팀 참가 가능.' },
  { term: 'PRO', desc: '선수 등록·경력 제한이 있는 상위 레벨 대회.' },
  { term: 'AMATEUR', desc: '비선출·아마추어 전용 레벨. 참가 자격 심사 있음.' },
  { term: '더블 엘리미네이션', desc: '두 번 패할 때까지 탈락하지 않는 대진 방식.' },
  { term: '싱글 엘리미네이션', desc: '한 번 패하면 탈락하는 대진 방식. 짧은 대회에 적합.' },
  { term: '레이팅', desc: '경기 결과 기반 계산되는 팀·선수 실력 지표. 기본값 1500.' },
  { term: '승률', desc: '승 / (승 + 패) × 100. 시즌 단위로 집계.' },
  { term: 'PPG / APG / RPG', desc: '경기당 평균 득점 / 어시스트 / 리바운드.' },
  { term: 'D-N', desc: '접수 마감까지 남은 일 수. D-0은 오늘 마감.' },
  { term: '운영진', desc: '대회·경기·커뮤니티를 관리하는 BDR 공식 스태프.' },
];

const HELP_FAQ = [
  { q: '팀 등록은 어떻게 하나요?', a: '상단 메뉴 [팀] → [팀 등록] 버튼으로 최소 3명 이상이 모인 팀을 등록할 수 있습니다. 팀장 1명, 부팀장 1명, 팀원 1명이 기본 구성입니다.' },
  { q: '대회 신청 후 취소할 수 있나요?', a: '접수 마감 3일 전까지는 자유롭게 취소 가능하며, 참가비는 100% 환불됩니다. 이후에는 50%만 환불됩니다.' },
  { q: '레이팅은 어떻게 계산되나요?', a: '기본 1500에서 시작하여, 각 경기의 승패·점수차·상대 레이팅에 따라 매 경기 ±5~±40 변동됩니다.' },
  { q: '픽업과 게스트의 차이는?', a: '픽업은 개인 단위로 모여 즉석 팀을 구성하는 것이고, 게스트는 기존 팀의 부족한 인원을 일회성으로 채우는 역할입니다.' },
  { q: '대회 성적은 어디에 반영되나요?', a: 'OPEN·PRO 대회는 팀 레이팅에 반영되고, 선수별 기록(PPG/APG/RPG)은 개인 프로필과 선수 랭킹에 반영됩니다.' },
  { q: '유료 멤버십은 꼭 필요한가요?', a: '아니요. 기본 기능은 모두 무료입니다. PRO 멤버십은 대회 우선 접수·상세 통계·광고 제거 등 편의 기능입니다.' },
];

// ========== PRICING ==========
const PRICING = [
  {
    id: 'free',
    name: 'FREE',
    price: '₩0',
    subprice: '영원히',
    tagline: '시작하기에 충분합니다',
    features: [
      '커뮤니티 전체 이용',
      '픽업·게스트 신청',
      '팀 1개 등록',
      '기본 레이팅·승률 확인',
      '주간 대회 열람',
    ],
    cta: '지금 시작',
    highlight: false,
  },
  {
    id: 'plus',
    name: 'BDR+',
    price: '₩4,900',
    subprice: '/월',
    tagline: '주말을 더 자주 뛰는 사람을 위해',
    features: [
      'FREE의 모든 기능',
      '대회 우선 접수 (12시간 먼저)',
      '상세 선수 스탯·경기 리플레이',
      '팀 3개까지 등록',
      '광고 제거',
      '팀 배너·엠블럼 업로드',
    ],
    cta: '14일 무료 체험',
    highlight: true,
  },
  {
    id: 'pro',
    name: 'PRO',
    price: '₩29,000',
    subprice: '/월 · 팀당',
    tagline: '리그·단체 운영팀용',
    features: [
      'BDR+의 모든 기능',
      '리그·단체 운영 대시보드',
      '대진표·일정 자동 생성',
      '심판·경기 기록 시스템',
      '전용 CS 라인',
      '자체 도메인 페이지',
    ],
    cta: '문의하기',
    highlight: false,
  },
];

// ========== OPEN RUN (즉석 매칭, 30분 안에 코트 가는 행동) ==========
// pickup과의 차이: 일정이 미리 잡힌 게 아니라 "지금/곧" 시작 — 도착 ETA 기반
const OPEN_RUNS = [
  {
    id: 'or1',
    court: '용산국민체육센터',
    area: '용산구',
    indoor: true,
    startsIn: 12,            // 분 후 시작
    duration: 90,
    format: '3v3',
    level: '중급+',
    needs: 2,                // 더 필요한 인원
    on: 4,                   // 현재 모인 인원
    fee: '₩4,000',
    host: 'rdm_captain',
    note: '하프코트 1면 잡았어요. 풀코트 가능하면 6명까지.',
    vibes: ['진지함', '경쟁'],
    distanceKm: 1.4,
  },
  {
    id: 'or2',
    court: '반포한강 농구장',
    area: '서초구',
    indoor: false,
    startsIn: 28,
    duration: 120,
    format: '5v5',
    level: '전연령',
    needs: 3,
    on: 7,
    fee: '무료',
    host: 'pivot_mia',
    note: '날씨 맑음. 음수대 옆 코트.',
    vibes: ['캐주얼', '초보환영'],
    distanceKm: 3.8,
  },
  {
    id: 'or3',
    court: '강변테크노마트 스카이코트',
    area: '광진구',
    indoor: true,
    startsIn: 0,             // 진행중
    duration: 60,
    format: '3v3',
    level: '상급',
    needs: 1,
    on: 5,
    fee: '₩6,000',
    host: 'kings_cap',
    note: '한 명만 더 오면 풀게임. ASAP.',
    vibes: ['진지함', 'ASAP'],
    distanceKm: 5.2,
    live: true,
  },
  {
    id: 'or4',
    court: '성동구민체육관',
    area: '성동구',
    indoor: true,
    startsIn: 60,
    duration: 120,
    format: '5v5',
    level: '중급',
    needs: 4,
    on: 6,
    fee: '₩5,000',
    host: 'block',
    note: '코트 1면 예약. 풀게임 만들면 5v5 갑니다.',
    vibes: ['캐주얼'],
    distanceKm: 6.1,
  },
  {
    id: 'or5',
    court: '회룡역사거리 농구장',
    area: '의정부시',
    indoor: false,
    startsIn: 45,
    duration: 90,
    format: '3v3',
    level: '초-중급',
    needs: 2,
    on: 2,
    fee: '무료',
    host: 'sunrise',
    note: '슛 연습부터 시작 → 게임으로.',
    vibes: ['초보환영', '연습'],
    distanceKm: 14.0,
  },
];

window.GAMES = GAMES;
window.ORGS = ORGS;
window.GLOSSARY = GLOSSARY;
window.HELP_FAQ = HELP_FAQ;
window.PRICING = PRICING;
window.OPEN_RUNS = OPEN_RUNS;
